ddataset:
    root_dir: "data/Extended-CMU-Seasons"
    name: "cmu"
    slice_list: [2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    pair_type: "cosplace10"
    test:
        topk_retrieval: 10
        img_size: 864
        n_pts: [50, 10000]

model:
    matcher:
        topicfm: {"match_coarse": {"thr": 0.25, "border_rm": 2}, "coarse": {"nhead": 2, "attention": "full", "n_samples": 0}}
        pretrained_ckpt: "third_party/feat_matcher/TopicFM/pretrained/topicfm_fast.ckpt"
        n_matches: 5000
    qt_size: 4

trainer:
    ransac_thr: 15
